import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LinkList from '../components/LinkList'
import { gql } from '@apollo/client';
import { client } from './_app'
const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LinkList linksToRender={data} />
      </main>
    </div>
  )
}

const FEED_QUERY = gql`
  {
    feed {
      id
      links {
        id
        createdAt
        url
        description
      }
    }
  }
`
  ;

export async function getServerSideProps() {
  const { data } = await client.query({
    query: FEED_QUERY
  })

  return { props: { data } }
}

export default Home
